ConfigVersion: 6.0
DeleteVillagerInventoryOnCatch: true
NonPlayerCatching: true
PreventCatchingBabyAnimals: true
PreventCatchingShearedSheeps: true
PreventCatchingTamedAnimals: true
SmokeEffect: true
SpawnChickenOnFail: true
SpawnChickenOnSuccess: true
UseCatchChance: true
UseHealthPercentage: true
UseItemCost: true
UsePermissions: true
UseVaultCost: true
ExplosionEffect: true
LogEggCaptures: true
LooseEggOnFail: true
setPersistence: true
VaultTargetBankAccount: ''
Entity:
  Axolotl:
    CatchChance: 100.0
    HealthPercentage: 100.0
    ItemCost:
      Amount: 0.0
      ItemName: gold_nugget
    VaultCost: 0.0
  Bat:
    CatchChance: 100.0
    HealthPercentage: 100.0
    ItemCost:
      Amount: 0.0
      ItemName: gold_nugget
    VaultCost: 0.0
  Bee:
    CatchChance: 100.0
    HealthPercentage: 100.0
    ItemCost:
      Amount: 0.0
      ItemName: gold_nugget
    VaultCost: 0.0
  Blaze:
    CatchChance: 100.0
    HealthPercentage: 100.0
    ItemCost:
      Amount: 0.0
      ItemName: gold_nugget
    VaultCost: 0.0
  Cat:
    CatchChance: 100.0
    HealthPercentage: 100.0
    ItemCost:
      Amount: 0.0
      ItemName: gold_nugget
    VaultCost: 0.0
  CaveSpider:
    CatchChance: 100.0
    HealthPercentage: 100.0
    ItemCost:
      Amount: 0.0
      ItemName: gold_nugget
    VaultCost: 0.0
  Chicken:
    CatchChance: 100.0
    HealthPercentage: 100.0
    ItemCost:
      Amount: 0.0
      ItemName: gold_nugget
    VaultCost: 0.0
  Cod:
    CatchChance: 100.0
    HealthPercentage: 100.0
    ItemCost:
      Amount: 0.0
      ItemName: gold_nugget
    VaultCost: 0.0
  Cow:
    CatchChance: 100.0
    HealthPercentage: 100.0
    ItemCost:
      Amount: 0.0
      ItemName: gold_nugget
    VaultCost: 0.0
  Creeper:
    CatchChance: 100.0
    HealthPercentage: 100.0
    ItemCost:
      Amount: 0.0
      ItemName: gold_nugget
    VaultCost: 0.0
  Dolphin:
    CatchChance: 100.0
    HealthPercentage: 100.0
    ItemCost:
      Amount: 0.0
      ItemName: gold_nugget
    VaultCost: 0.0
  Donkey:
    CatchChance: 100.0
    HealthPercentage: 100.0
    ItemCost:
      Amount: 0.0
      ItemName: gold_nugget
    VaultCost: 0.0
  Drowned:
    CatchChance: 100.0
    HealthPercentage: 100.0
    ItemCost:
      Amount: 0.0
      ItemName: gold_nugget
    VaultCost: 0.0
  ElderGuardian:
    CatchChance: 100.0
    HealthPercentage: 100.0
    ItemCost:
      Amount: 0.0
      ItemName: gold_nugget
    VaultCost: 0.0
  Enderman:
    CatchChance: 100.0
    HealthPercentage: 100.0
    ItemCost:
      Amount: 0.0
      ItemName: gold_nugget
    VaultCost: 0.0
  Endermite:
    CatchChance: 100.0
    HealthPercentage: 100.0
    ItemCost:
      Amount: 0.0
      ItemName: gold_nugget
    VaultCost: 0.0
  Evoker:
    CatchChance: 100.0
    HealthPercentage: 100.0
    ItemCost:
      Amount: 0.0
      ItemName: gold_nugget
    VaultCost: 0.0
  Fox:
    CatchChance: 100.0
    HealthPercentage: 100.0
    ItemCost:
      Amount: 0.0
      ItemName: gold_nugget
    VaultCost: 0.0
  Ghast:
    CatchChance: 100.0
    HealthPercentage: 100.0
    ItemCost:
      Amount: 0.0
      ItemName: gold_nugget
    VaultCost: 0.0
  GlowSquid:
    CatchChance: 100.0
    HealthPercentage: 100.0
    ItemCost:
      Amount: 0.0
      ItemName: gold_nugget
    VaultCost: 0.0
  Goat:
    CatchChance: 100.0
    HealthPercentage: 100.0
    ItemCost:
      Amount: 0.0
      ItemName: gold_nugget
    VaultCost: 0.0
  Guardian:
    CatchChance: 100.0
    HealthPercentage: 100.0
    ItemCost:
      Amount: 0.0
      ItemName: gold_nugget
    VaultCost: 0.0
  Hoglin:
    CatchChance: 100.0
    HealthPercentage: 100.0
    ItemCost:
      Amount: 0.0
      ItemName: gold_nugget
    VaultCost: 0.0
  Horse:
    CatchChance: 100.0
    HealthPercentage: 100.0
    ItemCost:
      Amount: 0.0
      ItemName: gold_nugget
    VaultCost: 0.0
  Husk:
    CatchChance: 100.0
    HealthPercentage: 100.0
    ItemCost:
      Amount: 0.0
      ItemName: gold_nugget
    VaultCost: 0.0
  Llama:
    CatchChance: 100.0
    HealthPercentage: 100.0
    ItemCost:
      Amount: 0.0
      ItemName: gold_nugget
    VaultCost: 0.0
  MagmaCube:
    CatchChance: 100.0
    HealthPercentage: 100.0
    ItemCost:
      Amount: 0.0
      ItemName: gold_nugget
    VaultCost: 0.0
  Mule:
    CatchChance: 100.0
    HealthPercentage: 100.0
    ItemCost:
      Amount: 0.0
      ItemName: gold_nugget
    VaultCost: 0.0
  MushroomCow:
    CatchChance: 100.0
    HealthPercentage: 100.0
    ItemCost:
      Amount: 0.0
      ItemName: gold_nugget
    VaultCost: 0.0
  Ocelot:
    CatchChance: 100.0
    HealthPercentage: 100.0
    ItemCost:
      Amount: 0.0
      ItemName: gold_nugget
    VaultCost: 0.0
  Panda:
    CatchChance: 100.0
    HealthPercentage: 100.0
    ItemCost:
      Amount: 0.0
      ItemName: gold_nugget
    VaultCost: 0.0
  Parrot:
    CatchChance: 100.0
    HealthPercentage: 100.0
    ItemCost:
      Amount: 0.0
      ItemName: gold_nugget
    VaultCost: 0.0
  Phantom:
    CatchChance: 100.0
    HealthPercentage: 100.0
    ItemCost:
      Amount: 0.0
      ItemName: gold_nugget
    VaultCost: 0.0
  Pig:
    CatchChance: 100.0
    HealthPercentage: 100.0
    ItemCost:
      Amount: 0.0
      ItemName: gold_nugget
    VaultCost: 0.0
  PigZombie:
    CatchChance: 100.0
    HealthPercentage: 100.0
    ItemCost:
      Amount: 0.0
      ItemName: gold_nugget
    VaultCost: 0.0
  Piglin:
    CatchChance: 100.0
    HealthPercentage: 100.0
    ItemCost:
      Amount: 0.0
      ItemName: gold_nugget
    VaultCost: 0.0
  PiglinBrute:
    CatchChance: 100.0
    HealthPercentage: 100.0
    ItemCost:
      Amount: 0.0
      ItemName: gold_nugget
    VaultCost: 0.0
  Pillager:
    CatchChance: 100.0
    HealthPercentage: 100.0
    ItemCost:
      Amount: 0.0
      ItemName: gold_nugget
    VaultCost: 0.0
  PolarBear:
    CatchChance: 100.0
    HealthPercentage: 100.0
    ItemCost:
      Amount: 0.0
      ItemName: gold_nugget
    VaultCost: 0.0
  Pufferfish:
    CatchChance: 100.0
    HealthPercentage: 100.0
    ItemCost:
      Amount: 0.0
      ItemName: gold_nugget
    VaultCost: 0.0
  Rabbit:
    CatchChance: 100.0
    HealthPercentage: 100.0
    ItemCost:
      Amount: 0.0
      ItemName: gold_nugget
    VaultCost: 0.0
  Ravager:
    CatchChance: 100.0
    HealthPercentage: 100.0
    ItemCost:
      Amount: 0.0
      ItemName: gold_nugget
    VaultCost: 0.0
  Salmon:
    CatchChance: 100.0
    HealthPercentage: 100.0
    ItemCost:
      Amount: 0.0
      ItemName: gold_nugget
    VaultCost: 0.0
  Sheep:
    CatchChance: 100.0
    HealthPercentage: 100.0
    ItemCost:
      Amount: 0.0
      ItemName: gold_nugget
    VaultCost: 0.0
  Shulker:
    CatchChance: 100.0
    HealthPercentage: 100.0
    ItemCost:
      Amount: 0.0
      ItemName: gold_nugget
    VaultCost: 0.0
  Silverfish:
    CatchChance: 100.0
    HealthPercentage: 100.0
    ItemCost:
      Amount: 0.0
      ItemName: gold_nugget
    VaultCost: 0.0
  Skeleton:
    CatchChance: 100.0
    HealthPercentage: 100.0
    ItemCost:
      Amount: 0.0
      ItemName: gold_nugget
    VaultCost: 0.0
  SkeletonHorse:
    CatchChance: 100.0
    HealthPercentage: 100.0
    ItemCost:
      Amount: 0.0
      ItemName: gold_nugget
    VaultCost: 0.0
  Slime:
    CatchChance: 100.0
    HealthPercentage: 100.0
    ItemCost:
      Amount: 0.0
      ItemName: gold_nugget
    VaultCost: 0.0
  Spider:
    CatchChance: 100.0
    HealthPercentage: 100.0
    ItemCost:
      Amount: 0.0
      ItemName: gold_nugget
    VaultCost: 0.0
  Squid:
    CatchChance: 100.0
    HealthPercentage: 100.0
    ItemCost:
      Amount: 0.0
      ItemName: gold_nugget
    VaultCost: 0.0
  Stray:
    CatchChance: 100.0
    HealthPercentage: 100.0
    ItemCost:
      Amount: 0.0
      ItemName: gold_nugget
    VaultCost: 0.0
  Strider:
    CatchChance: 100.0
    HealthPercentage: 100.0
    ItemCost:
      Amount: 0.0
      ItemName: gold_nugget
    VaultCost: 0.0
  TraderLlama:
    CatchChance: 100.0
    HealthPercentage: 100.0
    ItemCost:
      Amount: 0.0
      ItemName: gold_nugget
    VaultCost: 0.0
  TropicalFish:
    CatchChance: 100.0
    HealthPercentage: 100.0
    ItemCost:
      Amount: 0.0
      ItemName: gold_nugget
    VaultCost: 0.0
  Turtle:
    CatchChance: 100.0
    HealthPercentage: 100.0
    ItemCost:
      Amount: 0.0
      ItemName: gold_nugget
    VaultCost: 0.0
  Vex:
    CatchChance: 100.0
    HealthPercentage: 100.0
    ItemCost:
      Amount: 0.0
      ItemName: gold_nugget
    VaultCost: 0.0
  Villager:
    CatchChance: 100.0
    HealthPercentage: 100.0
    ItemCost:
      Amount: 0.0
      ItemName: gold_nugget
    VaultCost: 0.0
  Vindicator:
    CatchChance: 100.0
    HealthPercentage: 100.0
    ItemCost:
      Amount: 0.0
      ItemName: gold_nugget
    VaultCost: 0.0
  WanderingTrader:
    CatchChance: 100.0
    HealthPercentage: 100.0
    ItemCost:
      Amount: 0.0
      ItemName: gold_nugget
    VaultCost: 0.0
  Witch:
    CatchChance: 100.0
    HealthPercentage: 100.0
    ItemCost:
      Amount: 0.0
      ItemName: gold_nugget
    VaultCost: 0.0
  WitherSkeleton:
    CatchChance: 100.0
    HealthPercentage: 100.0
    ItemCost:
      Amount: 0.0
      ItemName: gold_nugget
    VaultCost: 0.0
  Wolf:
    CatchChance: 100.0
    HealthPercentage: 100.0
    ItemCost:
      Amount: 0.0
      ItemName: gold_nugget
    VaultCost: 0.0
  Zoglin:
    CatchChance: 100.0
    HealthPercentage: 100.0
    ItemCost:
      Amount: 0.0
      ItemName: gold_nugget
    VaultCost: 0.0
  Zombie:
    CatchChance: 100.0
    HealthPercentage: 100.0
    ItemCost:
      Amount: 0.0
      ItemName: gold_nugget
    VaultCost: 0.0
  ZombieHorse:
    CatchChance: 100.0
    HealthPercentage: 100.0
    ItemCost:
      Amount: 0.0
      ItemName: gold_nugget
    VaultCost: 0.0
  ZombieVillager:
    CatchChance: 100.0
    HealthPercentage: 100.0
    ItemCost:
      Amount: 0.0
      ItemName: gold_nugget
    VaultCost: 0.0
  ZombifiedPiglin:
    CatchChance: 100.0
    HealthPercentage: 100.0
    ItemCost:
      Amount: 0.0
      ItemName: gold_nugget
    VaultCost: 0.0
Messages:
  CatchChanceFail: You failed to catch this mob!
  CatchChanceSuccess: ''
  HealthPercentageFail: The mob has more than %s percent health left and cannot be
    caught!
  ItemCostFail: It costs %s gold nugget(s) to catch this mob!
  ItemCostSuccess: You paid %s gold nugget(s) for catching this mob!
  PermissionFail: You do not have permission to catch this mob!
  VaultFail: It costs %s dollars to catch this mob!
  VaultSuccess: You paid %s dollars for catching this mob!
